apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: "redis-6"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        name: "redis-6"
    spec:
      nodeName: node-02
      hostNetwork: true
      containers:
        - name: redis
          image: "index.alauda.cn/yjgai/redis:6384"
          command:
            - "redis-server"
          args:
            - "/etc/redis/redis.conf"
            - "--protected-mode"
            - "no"
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
          ports:
            - name: redis
              containerPort: 6384
              protocol: "TCP"
            - name: cluster
              containerPort: 16384
              protocol: "TCP"
          volumeMounts:
            - name: "redis-data"
              mountPath: "/var/lib/redis"
      volumes:
        - name: "redis-data"
          emptyDir: {}
